### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by rafatabbas** [gitcoinco/code_fund_ads#787] opened 2019-11-06 13:43 UTC
Hi, 
am new to ruby, is there a quick guide on how to install codefund in development or production?
many thanks

**Comment by andrewmcodes** [comment] 2019-11-06 15:30
Hi @rafatabbas!

Here are the instructions for getting your development environment up and running. Let us know if you run into an issues! 

https://github.com/gitcoinco/code_fund_ads#development-environment

**Comment by rafatabbas** [comment] 2019-11-07 06:26
Hi @andrewmcodes 

when i run # db setup + tests using the following command;

rails db:create db:migrate

i get an error message;

FATAL:  password authentication failed for user "myusername"
FATAL:  password authentication failed for user "myusername"
Couldn't create 'mydatabase' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "myusername"
FATAL:  password authentication failed for user "myusername"
bin/rails:9:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

here is my .env and database.yml file;

https://pastebin.com/fKezX6C4

https://pastebin.com/WgTTsdh7

**Comment by andrewmcodes** [comment] 2019-11-07 08:13
@rafatabbas what operating system are you on? 

Off the bat I’m guessing you don’t have a user named `myusername` in Postgres. You can verify by trying to access Postgres using their cli tool with the credentials you are providing. 

Without knowing your OS, you probably want this is your .env:

```
# you should not change this
export PG_DATABASE_NAME='code_fund_ads_development'
# default Postgres password is blank
export PG_PASSWORD=
# I don’t think you’d need to set this
export PG_URL=
# default Postgres username is ‘postgres’
export PG_USERNAME=postgres 
```

**Comment by rafatabbas** [comment] 2019-11-07 11:18
Hi @andrewmcodes 

am using ubuntu 18.04 bionic with node 13.0.1

I did the suggested config to .env file but i get the following error:

fe_sendauth: no password supplied
Couldn't create 'code_fund_ads_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
bin/rails:9:in `<main>'
Tasks: TOP => db:create

**Comment by andrewmcodes** [comment] 2019-11-07 16:16
@rafatabbas set a password for your `postgres` user on the psql cli or create a new user with a password and use that user and password. 

Let me know if you can’t figure it out and we can schedule some time to pair.

**Comment by rafatabbas** [comment] 2019-11-10 13:05
Hi @andrewmcodes, i have set a new password for `postgres` , but after running `rails s` i get his error on 127.0.0.1:3000 

An error has occurred, this and all later migrations canceled: PG::WrongObjectType: ERROR: cannot create index on partitioned table "impressions"

`Extracted source (around line #90):`

`log(sql, name) do
            ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
              @connection.async_exec(sql)
            end
          end
        end`

**Comment by andrewmcodes** [comment] 2019-11-11 14:55
@rafatabbas have you enabled development caching per the docs?
`bundle exec rails dev:cache`

Have you seeded your database? Try running `rails db:reset`.

**Comment by rafatabbas** [comment] 2019-11-12 07:52
Hi @andrewmcodes cache is already enabled.

when i run `rails db:reset` i get the following errors:

`rails db:reset
Dropped database 'code_fund_ads_development'
Dropped database 'code_fund_ads_test'
Created database 'code_fund_ads_development'
Created database 'code_fund_ads_test'
 set_config 
------------
 
(1 row)

psql:/home/username/code_fund_ads/db/structure.sql:543: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...essions ATTACH PARTITION public.impressions_default DEFAULT;
                                                               ^
rails aborted!
failed to execute:
psql -v ON_ERROR_STOP=1 -q -X -f /home/username/code_fund_ads/db/structure.sql code_fund_ads_development

Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.

bin/rails:9:in `<main>'
Tasks: TOP => db:structure:load
(See full trace by running task with --trace)`

**Comment by andrewmcodes** [comment] 2019-11-12 15:18
@rafatabbas Have you confirmed this is true? 
```
Please check the output above for any errors and make sure that psql is installed in your PATH and has proper permissions.
```

It sounds like maybe your Postgres user is set up incorrectly. I ran the same command to confirm and I did not have any issues. I would imagine you'd run into this issue on any rails app if you specifically specify the username and password. I would read the Postgres documentation. [This](https://www.digitalocean.com/community/tutorials/how-to-use-roles-and-manage-grant-permissions-in-postgresql-on-a-vps--2) may also be helpful.

@cmckee-dev can you chime in here since you are also on ubuntu?

**Comment by cmckee-dev** [comment] 2019-11-12 18:47
@rafatabbas I'll chime in here. Can you check these things for me:

1. Can you check that you're using Postgresql-11. Also if you need to install **or** installed 11 ontop of a previous version, can you check you have version 11 and set it as the `main` for your pg_cluster. 
```
$ pg_lsclusters  

Ver Cluster Port Status Owner    Data directory              Log file
11  main    5432 online postgres /var/lib/postgresql/11/main /var/log/postgresql/postgresql-11-main.log
```  
2. If that looks good then can we double check the users on postgres. There is some odd cases were postgres tries to use the same `username` as the `whoami` username instead of `postgres`. Lets just double check:  

```
psql

psql (11.5 (Ubuntu 11.5-3.pgdg18.04+1))
Type "help" for help.

cmckee=#\du  

                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 cmckee    | Superuser, Create role, Create DB                          | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
.
.
.

cmckee=#\l

                                          List of databases
           Name            |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
---------------------------+----------+----------+-------------+-------------+-----------------------
 cmckee                    | cmckee   | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 code_fund_ads_development | cmckee   | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 code_fund_ads_test        | cmckee   | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres                  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
.
.
.
```

**Note:** Just because you see `psql (11.5 (Ubuntu 11.5-3.pgdg18.04+1))` or something similar at the top when you log into `psql` doesn't mean it uses it. Make sure you check the first step.

Let me know what you come up with for both of those.

**Comment by rafatabbas** [comment] 2019-11-13 11:52
Hi @cmckee-dev @andrewmcodes  Thank you guys, it was postgresql-10, so i removed that and installed a fresh postgresql-11, everything went okay and frontpage started to load on localhost:3000 but it disconnects and throws a continuous error in the terminal:

`home/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
[30286] - Worker 0 (pid: 31854) booted, phase: 0
Started GET "/cable" for ::1 at 2019-11-13 13:42:01`

**Comment by cmckee-dev** [comment] 2019-11-13 16:37
@rafatabbas Good to hear! Yeah, we have some cool logic with our PG instance that requires version 11. I believe we require version 5 on Redis as well. Update that and let me know how that goes.

**Comment by andrewmcodes** [comment] 2019-11-13 20:20
@rafatabbas in addition to what @cmckee-dev said, you need to make sure Redis is running locally on your computer.

**Comment by rafatabbas** [comment] 2019-11-14 10:13
Thanks @cmckee-dev @andrewmcodes it works perfect now but page loads very slow!
and when i click on blog link i get this error; also how to access the admin area so I can create ads, users and campaigns.

`Net::OpenTimeout in Buttercms::PostsController#index

execution expired

Extracted source (around line #3):
1
2
3
4
5
6
              
class Buttercms::PostsController < Buttercms::BaseController
  def index
    @posts = ButterCMS::Post.all(page: params[:page], page_size: 12)

    @next_page = @posts.meta.next_page
    @previous_page = @posts.meta.previous_page`

**Comment by andrewmcodes** [comment] 2019-11-14 14:03
@rafatabbas have you enabled development caching per the docs?
```
bundle exec rails dev:cache
```

With regards to the blog, we have actually moved that out of the app, we just haven’t completely removed the code for it yet. Probably something we should do sooner or later. We are in the middle of a total redesign of the app so some things may seem a little wonky in development. 

To access the administrator controls in the app, your user needs to have the administrator role. 

https://github.com/gitcoinco/code_fund_ads/blob/fa54466589f870a39125e42bfb64f0e9eeb59303/db/schema.rb#L495

Just update your user and you should be able to access the admin controls. 

If it’s ok with you I think this issue is good to close. If you’d like to discuss other things about the app, feel free to drop into gitter (link is on the readme). I’ll close this in two days unless you run into any more issues with running the app. 

@cmckee-dev if you have some spare time, can you look into removing the blog related stuff from the app? Ty ❤️

**Closed** 2019-11-14 16:20 UTC
Labels: question
